# Generated by Django 4.1.7 on 2024-10-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('publisher', models.CharField(max_length=255, null=True)),
                ('year', models.DateField(null=True)),
                ('isbn', models.CharField(max_length=255, null=True)),
                ('backcover', models.TextField(null=True)),
                ('cover', models.BooleanField(null=True)),
            ],
        ),
    ]
