# Generated by Django 4.2.16 on 2024-11-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0005_alter_book_cover_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('books', models.ManyToManyField(related_name='authors', to='bonnes_lectures.book')),
                ('reviews', models.ManyToManyField(related_name='authors', to='bonnes_lectures.review')),
            ],
        ),
    ]
