# Generated by Django 4.2.16 on 2024-11-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0007_rename_name_author_nom_author_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('authors', models.ManyToManyField(related_name='users', to='bonnes_lectures.author')),
                ('books', models.ManyToManyField(related_name='users', to='bonnes_lectures.book')),
                ('reviews', models.ManyToManyField(related_name='users', to='bonnes_lectures.review')),
            ],
        ),
    ]
