# Generated by Django 4.2.16 on 2024-11-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0011_remove_author_books_remove_author_reviews_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='authors',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
