# Generated by Django 4.2.16 on 2024-11-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0012_rename_publisher_book_authors_remove_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=255, null=True)),
                ('num_editeur', models.CharField(max_length=255, null=True)),
                ('num_publication', models.CharField(max_length=255, null=True)),
                ('cle', models.CharField(max_length=255, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbn', to='bonnes_lectures.book')),
            ],
        ),
    ]
