# Generated by Django 4.2.16 on 2024-11-26 11:06

import bonnes_lectures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0013_remove_book_isbn_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isbn',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=bonnes_lectures.models.IsbnField(default=1, max_length=17),
            preserve_default=False,
        ),
    ]
