services:
 base:
  build:
    context: .
    dockerfile: Dockerfile_tp5
    args:
      USERNAME: 
      USERID: 
  container_name: fw1-tp5-${USERNAME}
  command: /bin/bash
  tty: true
  stdin_open: true
  volumes:
  - .:/home/user/workspace
  ports:
  - "8088:8000"
  environment:
    PS1: "[ $$(whoami) | \\w ] "